version: "3.5"

services:
  golang-crossbuild-arm:
    image: beer5215/golang-crossbuild-arm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-crossbuild-arm
    restart: always

